// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CalculadoraTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void calculadora() {
    driver.get("http://127.0.0.1:5501/Web/Calculadora/calculadora.html");
    driver.manage().window().setSize(new Dimension(1211, 678));
    driver.findElement(By.cssSelector(".numero:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(10)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(12)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(10)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(10)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(11)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(15)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(9)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".calculadora")).click();
    driver.findElement(By.cssSelector(".calculadora")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".calculadora"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".numero:nth-child(17)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".numero:nth-child(17)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(16)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".numero:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".operador:nth-child(18)")).click();
    driver.findElement(By.cssSelector(".col-2:nth-child(1)")).click();
  }
}
